### ISSUE TITLE
node attributes

### ISSUE THREAD

**Issue by margokhokhlova** [tvayer/FGW#1]
Did you actually try to use node attributes in your work?
Current code doesn't allow for that, expecting discreet node labels only:
labels = np.zeros(len(l_aux), dtype=np.int32), so the moment I try to upload a dataset with attributes, the code crashes..
I wrote a workaround where I use labels as strings to put node features there, but not sure if it is feasible to do since node attributes are very different...

**Comment by margokhokhlova** [comment]
PS: Thank you very much in advance!

**Comment by tvayer** [comment]
Hello, 
In data_loader.py you can choose to use the vector attributes of the data when calling load_local_data (by setting attributes=True) for most of the datasets. Then for FGW you can use any distances between the labels with the features_metric parameter (choices are dirac/hamming_dist for discret labels/sqeuclidean for vector attributes or any metric compatible with scipy https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html since it uses the metric param of POT to create the matrix here: https://github.com/tvayer/FGW/blob/ae26917abbc00da1ccc1a598ebdde56d5f60ea2f/lib/ot_distances.py#L159)

**Comment by margokhokhlova** [comment]
Thank you very much for your answer!
I think I got it, I was applying the WL function when I shouldn't in case
of non-integer labels. I am closing the issue.
